name: service_ui
on:
  pull_request:
    branches:
      - "main"
    paths:
      - 'elasticSearchApp/**'

jobs:
  service_pr_verification:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: running the unit tests
        working-directory: elasticSearchApp/
        run: mvn verify

      - name: running the unit tests
        working-directory: elasticSearchApp/
        run: mvn clean install
        
