name: build and push into docker
on:
  push:
    branches:
      - "main"
    paths:
      - 'elasticSearchApp/**'

jobs:
  build_jar_and_image_and_push_to_registry:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: build the app
        working-directory: elasticSearchApp/
        run: mvn clean install
        
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./elasticSearchApp
          file: ./elasticSearchApp/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/service:latest
      -
        name: shutting down previous image
        working-directory: docker/
        run: docker compose down
      -
        name: pulling latest changes
        working-directory: docker/
        run: docker compose pull
      -
        name: starting the latest images
        working-directory: docker/
        run: docker compose up -d