name: build and push into docker
on:
  push:
    branches:
      - "main"
    paths:
      - 'elasticSearchApp/**'

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: build the app
        working-directory: elasticSearchApp/
        run: mvn clean install
