name: ui_change_triggered

on:
  push:
    branches:
      - "main"
    paths:
      - 'PlayerManagementUi/**'

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./PlayerManagementUi
          file: ./PlayerManagementUi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ui:latest
      -
        name: shutting down previous image
        working-directory: docker/
        run: docker compose down
      -
        name: pulling latest changes
        working-directory: docker/
        run: docker compose pull
      -
        name: starting the latest images
        working-directory: docker/
        run: docker compose up -d
