name: ui_ci

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'PlayerManagementUi/**'
    
    
jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16.11
        uses: actions/setup-node@v1
        with:
          node-version: 16.11

      - name: Install dependencies
        working-directory: PlayerManagementUi/
        run: npm install


      - name: running the unit tests
        working-directory: PlayerManagementUi/
        run: npm run test:ci



